version: '3.7'
services:
  node:
    image: node:16-alpine
    user: "node"
    ports:
      - '9999:9999'
    working_dir: /home/node/app
    volumes:
      - ./gate-simulator/:/home/node/app
    command: "npm start"

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres_service:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
